behaviors:
  MazeKeySearch:
    trainer_type: ppo
    time_horizon: 256
    max_steps: 1e6
    hyperparameters:
      learning_rate: 1e-4
      batch_size: 512
      buffer_size: 4096
      num_epoch: 3
    network_settings:
      num_layers: 3
      hidden_units: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
    summary_freq: 5000
    